#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : llvm
Version  : 12.0.1
Release  : 131
URL      : file:///insilications/apps/llvm-12.0.1.tar.gz
Source0  : file:///insilications/apps/llvm-12.0.1.tar.gz
Summary  : Google microbenchmark framework
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
BuildRequires : PyYAML
BuildRequires : Pygments
BuildRequires : Sphinx
BuildRequires : Vulkan-Headers-dev Vulkan-Loader-dev Vulkan-Tools
BuildRequires : Z3-dev
BuildRequires : binutils-dev
BuildRequires : binutils-extras
BuildRequires : bison
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-golang
BuildRequires : cmake
BuildRequires : dejagnu
BuildRequires : docbook-utils
BuildRequires : docbook-xml
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : expect
BuildRequires : flex
BuildRequires : gcc
BuildRequires : gcc-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-doc
BuildRequires : gcc-go
BuildRequires : gcc-go-lib
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libs-math
BuildRequires : gcc-libstdc++32
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : gdb-dev
BuildRequires : git
BuildRequires : glibc-bin
BuildRequires : glibc-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-doc
BuildRequires : glibc-extras
BuildRequires : glibc-lib-avx2
BuildRequires : glibc-libc32
BuildRequires : glibc-locale
BuildRequires : glibc-nscd
BuildRequires : glibc-staticdev
BuildRequires : glibc-utils
BuildRequires : gmp-dev
BuildRequires : googletest-dev
BuildRequires : graphviz
BuildRequires : grep
BuildRequires : guile
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libffi-dev
BuildRequires : libgcc1
BuildRequires : libstdc++
BuildRequires : libunwind-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt
BuildRequires : lua-dev
BuildRequires : mpc-dev
BuildRequires : mpfr-dev
BuildRequires : ncurses
BuildRequires : ncurses-abi
BuildRequires : ncurses-bin
BuildRequires : ncurses-data
BuildRequires : ncurses-dev
BuildRequires : ncurses-dev32
BuildRequires : ncurses-lib
BuildRequires : ncurses-lib-narrow
BuildRequires : ncurses-lib-plusplus
BuildRequires : ncurses-lib32
BuildRequires : ninja
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(libedit)
BuildRequires : pkgconfig(libffi)
BuildRequires : pkgconfig(zlib)
BuildRequires : procps-ng
BuildRequires : protobuf-dev
BuildRequires : ptyprocess
BuildRequires : pybind11-python3
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : sed
BuildRequires : swig
BuildRequires : tcl
BuildRequires : texinfo
BuildRequires : util-linux
BuildRequires : valgrind-dev
BuildRequires : xz-dev
BuildRequires : yaml
BuildRequires : yaml-cpp
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-llvm-Improve-physical-core-count-detection.patch
Patch2: 0002-llvm-Allow-one-more-FMA-fusion.patch
Patch3: 0004-llvm-Add-the-LLVM-major-version-number-to-the-Gold-L.patch
Patch4: 0005-llvm-Add-a-couple-more-f-instructions-that-GCC-has-t.patch

%description
Polly - Polyhedral optimizations for LLVM
-----------------------------------------
http://polly.llvm.org/

%prep
%setup -q -n llvm-12.0.1
cd %{_builddir}/llvm-12.0.1
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1620005851
unset LD_AS_NEEDED
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
## altflags1 content
export CCACHE_DISABLE=true
export V=1
export VERBOSE=1
export PATH="/usr/lib64/ccache/bin:$PATH"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#
unset ASFLAGS
unset LDFLAGS
unset CFLAGS
unset CXXFLAGS
unset FCFLAGS
unset FFLAGS
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#  --no-gc-sections -ffunction-sections -fdata-sections  -Wl,--no-as-needed -pthread -lpthread clang-tools-extra
export CFLAGS="-O3 -flto=16 -ffat-lto-objects -fuse-ld=bfd -fuse-linker-plugin -march=native -mtune=native -Wall -Wl,-O2 -Wl,--build-id=sha1 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -malign-data=cacheline -Wl,-sort-common -fdevirtualize-at-ltrans -flifetime-dse=1 -Wl,--as-needed -static-libgcc -static-libstdc++ -fPIC -pipe"
export CXXFLAGS="-O3 -flto=16 -ffat-lto-objects -fuse-ld=bfd -fuse-linker-plugin -march=native -mtune=native -Wall -Wl,-O2 -Wl,--build-id=sha1 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -malign-data=cacheline -Wl,-sort-common -fdevirtualize-at-ltrans -flifetime-dse=1 -Wl,--as-needed -static-libgcc -static-libstdc++ -fPIC -pipe"
export LDFLAGS="-O3 -flto=16 -ffat-lto-objects -fuse-ld=bfd -fuse-linker-plugin -march=native -mtune=native -Wall -Wl,-O2 -Wl,--build-id=sha1 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -malign-data=cacheline -Wl,-sort-common -fdevirtualize-at-ltrans -flifetime-dse=1 -Wl,--as-needed -static-libgcc -static-libstdc++ -fPIC -pipe"
## altflags1 end
# pushd ..
# sd "flto=full" "flto=16" -r "*.cmake"
# popd
cmake -G Ninja ../llvm \
    -DBUILD_SHARED_LIBS:BOOL=OFF \
    -DLIB_INSTALL_DIR=%{_libdir} \
    -DLIB_SUFFIX=64 \
    -DLLVM_LIBDIR_SUFFIX=64 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=gcc \
    -DCMAKE_CXX_COMPILER=g++ \
    -DCMAKE_INSTALL_LIBDIR=%{_libdir} \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_SBINDIR=%{_sbindir} \
    -DLLVM_PARALLEL_COMPILE_JOBS:STRING=16 \
    -DLLVM_PARALLEL_LINK_JOBS:STRING=6 \
    -DCMAKE_AR=/usr/bin/gcc-ar \
    -DCMAKE_NM=/usr/bin/gcc-nm \
    -DCMAKE_RANLIB=/usr/bin/gcc-ranlib \
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
    -DENABLE_LINKER_BUILD_ID:BOOL=ON \
    -DCLANG_BUILD_TOOLS:BOOL=ON \
    -DCLANG_DEFAULT_LINKER=lld \
    -DLLVM_ENABLE_LIBCXX:BOOL=OFF \
    -DLLVM_STATIC_LINK_CXX_STDLIB:BOOL=ON \
    -DCLANG_DEFAULT_CXX_STDLIB:STRING=libstdc++ \
    -DCLANG_ENABLE_STATIC_ANALYZER:BOOL=ON \
    -DCLANG_INCLUDE_TESTS:BOOL=OFF \
    -DCLANG_LINK_CLANG_DYLIB:BOOL=OFF \
    -DLLVM_LINK_LLVM_DYLIB:BOOL=OFF \
    -DLLVM_BUILD_LLVM_DYLIB:BOOL=ON \
    -DLIBCLANG_BUILD_STATIC:BOOL=ON \
    -DCOMPILER_RT_BUILD_SANITIZERS:BOOL=OFF \
    -DCOMPILER_RT_BUILD_XRAY:BOOL=OFF \
    -DLLVM_BINUTILS_INCDIR=/usr/include \
    -DLLVM_BUILD_EXAMPLES:BOOL=OFF \
    -DLLVM_BUILD_RUNTIME:BOOL=ON \
    -DLLVM_BUILD_TOOLS:BOOL=ON \
    -DLLVM_BUILD_UTILS:BOOL=ON \
    -DLLVM_ENABLE_ASSERTIONS:BOOL=OFF \
    -DLLVM_ENABLE_BINDINGS:BOOL=OFF \
    -DLLVM_ENABLE_DOXYGEN:BOOL=OFF \
    -DLLVM_ENABLE_EH:BOOL=ON \
    -DLLVM_ENABLE_LIBXML2:BOOL=ON \
    -DLLVM_ENABLE_RTTI:BOOL=ON \
    -DLLVM_REQUIRES_RTTI:BOOL=ON \
    -DLLVM_ENABLE_THREADS:BOOL=ON \
    -DLLVM_ENABLE_Z3_SOLVER:BOOL=ON \
    -DLLVM_ENABLE_LIBEDIT:BOOL=ON \
    -DLLVM_ENABLE_TERMINFO:BOOL=ON \
    -DLLVM_ENABLE_ZLIB:BOOL=ON \
    -DLLVM_ENABLE_FFI:BOOL=ON \
    -DFFI_INCLUDE_DIR=`pkg-config --variable=includedir libffi` \
    -DCLANG_ENABLE_ARCMT:BOOL=OFF \
    -DLLVM_INCLUDE_TESTS:BOOL=OFF \
    -DLLVM_INCLUDE_TOOLS:BOOL=ON \
    -DLLVM_INSTALL_UTILS:BOOL=ON \
    -DCMAKE_DISABLE_FIND_PACKAGE_CUDA:BOOL=ON \
    -DLLVM_OPTIMIZED_TABLEGEN:BOOL=ON \
    -DLLVM_ENABLE_PIC=ON \
    -DLLVM_TARGETS_TO_BUILD="X86" \
    -DLLVM_TOOL_CLANG_TOOLS_EXTRA_BUILD:BOOL=ON \
    -DLLVM_TOOL_COMPILER_RT_BUILD:BOOL=OFF \
    -DLLVM_USE_LINKER:STRING=bfd \
    -DLLVM_HOST_TRIPLE="x86_64-generic-linux" \
    -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
    -DLLVM_ENABLE_PLUGINS:BOOL=ON \
    -DLLVM_EXPORT_SYMBOLS_FOR_PLUGINS:BOOL=ON \
    -DLLVM_ENABLE_PROJECTS="llvm;clang;lld" \
    -DCMAKE_CXX_STANDARD:STRING="14" \
    -DCMAKE_C_FLAGS="-O3 -flto=16 -ffat-lto-objects -fuse-ld=bfd -fuse-linker-plugin -march=native -mtune=native -Wall -Wl,-O2 -Wl,--build-id=sha1 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -malign-data=cacheline -Wl,-sort-common -fdevirtualize-at-ltrans -flifetime-dse=1 -Wl,--as-needed -static-libgcc -static-libstdc++ -fPIC -pipe" \
    -DCMAKE_CXX_FLAGS="-O3 -flto=16 -ffat-lto-objects -fuse-ld=bfd -fuse-linker-plugin -march=native -mtune=native -Wall -Wl,-O2 -Wl,--build-id=sha1 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -malign-data=cacheline -Wl,-sort-common -fdevirtualize-at-ltrans -flifetime-dse=1 -Wl,--as-needed -static-libgcc -static-libstdc++ -fPIC -pipe" \
    -DCMAKE_EXE_LINKER_FLAGS="-O3 -flto=16 -ffat-lto-objects -fuse-ld=bfd -fuse-linker-plugin -march=native -mtune=native -Wall -Wl,-O2 -Wl,--build-id=sha1 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -malign-data=cacheline -Wl,-sort-common -fdevirtualize-at-ltrans -flifetime-dse=1 -Wl,--as-needed -static-libgcc -static-libstdc++ -fPIC -pipe" \
    -DCMAKE_MODULE_LINKER_FLAGS="-O3 -flto=16 -ffat-lto-objects -fuse-ld=bfd -fuse-linker-plugin -march=native -mtune=native -Wall -Wl,-O2 -Wl,--build-id=sha1 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -malign-data=cacheline -Wl,-sort-common -fdevirtualize-at-ltrans -flifetime-dse=1 -Wl,--as-needed -static-libgcc -static-libstdc++ -fPIC -pipe" \
    -DCMAKE_SHARED_LINKER_FLAGS="-O3 -flto=16 -ffat-lto-objects -fuse-ld=bfd -fuse-linker-plugin -march=native -mtune=native -Wall -Wl,-O2 -Wl,--build-id=sha1 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -malign-data=cacheline -Wl,-sort-common -fdevirtualize-at-ltrans -flifetime-dse=1 -Wl,--as-needed -static-libgcc -static-libstdc++ -fPIC -pipe" \
    -DGCC_INSTALL_PREFIX="/usr" \
    -Wno-dev
ninja --verbose -j16
## ccache stats
ccache -s
## ccache stats
popd

%install
export SOURCE_DATE_EPOCH=1620005851
rm -rf %{buildroot}
pushd clr-build
%ninja_install
popd
## install_append content
# Rename the tools to have a versioned suffix and symlink back
pushd %{buildroot}/usr/bin
mv clang ..
VERSION=%{version}
VERSION=${VERSION%%%%.*}
for f in *; do
case "$f" in
*-$VERSION)
# Already versioned, leave it alone
continue
;;
esac
if [ -L "$f" ]; then
# Retarget the symlink
ln -s -f `readlink $f`-$VERSION $f
fi
mv $f $f-$VERSION
ln -s -f $f-$VERSION $f
done
mv ../clang .
popd

# Ditto for the gold plugin
pushd %{buildroot}/usr/lib64
mv LLVMgold.so LLVMgold-$VERSION.so
mkdir -p ../lib/bfd-plugins
ln -s ../../lib64/LLVMgold-$VERSION.so ../lib/bfd-plugins
popd
## install_append end

%files
%defattr(-,root,root,-)
